---

- name: packages
  apt: pkg={{ item }}
  with_items:
      - postfix
      - ruby2.1
      - ruby
      - ruby-dev
      - libpq-dev
      - imagemagick
      - libmagickcore-dev
      - libmagickwand-dev
      - git
      - bundler
      - redis-server
      - rsync
      - build-essential
      - sudo
      - openssl

- block:
    - name: nginx package
      apt: pkg={{ item }}
      with_items:
          - nginx

    - name: site available
      template: src=cuttlefish.conf.j2
                dest=/etc/nginx/sites-available/cuttlefish.conf
      notify: restart nginx

    - name: site enabled
      file: state=link
            src=/etc/nginx/sites-available/cuttlefish.conf
            dest=/etc/nginx/sites-enabled/cuttlefish.conf
      notify: restart nginx

    # This task is very, very long
    - name: dhparam
      when: use_dhparam
      command: openssl dhparam -out /etc/ssl/private/dhparam.pem 4096
               create=/etc/ssl/private/dhparam.pem

    - name: ensure Nginx is started
      service: name=nginx state=started enabled=yes

  when: use_nginx
  tags: nginx

- name: cuttlefish user
  user: name=cuttlefish
        createhome=yes
        system=no
        state=present
        shell=/bin/bash
        groups=ssl-cert,adm
        #adm is for reading log

- name: cuttlefish home
  file: state=directory
        path=/home/cuttlefish
        owner=cuttlefish
        group=cuttlefish
        mode=0700

- name: cuttlefish is a sudoer
  copy: src=sudoers.d/cuttlefish dest=/etc/sudoers.d/cuttlefish
        mode=600
        owner=root
        group=root

- name: ssh folder
  file: path=/home/cuttlefish/.ssh
        state=directory
        owner=cuttlefish
        group=cuttlefish
        mode=0700

- name: root authorized keys
  command: cat /root/.ssh/authorized_keys
  register: authorized_root

- name: root can log as cuttlefish
  lineinfile: dest=/home/cuttlefish/.ssh/authorized_keys
              line="{{ item }}"
              create=yes
              owner=cuttlefish
              group=cuttlefish
              mode=600

  with_items: authorized_root.stdout_lines

- name: ssl certificate is readable
  file: path={{ item }}
        owner=root
        group=ssl-cert
        mode=640
  with_items:
      - "{{ cuttlefish_private_key }}"
      - "{{ cuttlefish_cert }}"

- name: env exist
  tags: systemd
  command: ls /home/cuttlefish/.env
  ignore_errors: True
  always_run: yes
  register: env_exists

- name: services
  tags: systemd
  copy: src=systemd/{{ item }} dest=/etc/systemd/system/{{ item }}
  with_items:
      - cuttlefish.service
      - cuttlefish-smtp.service
      - cuttlefish-log.service
      - cuttlefish-workers.service
      - cuttlefish-web.service
  notify: systemctl daemon-reload

- name: services are started
  tags: systemd
  service: name={{ item }} state=started enabled=yes
  with_items:
      - cuttlefish
      - cuttlefish-smtp
      - cuttlefish-log
      - cuttlefish-workers
      - cuttlefish-web
  when: env_exists.stderr == ''


#
# Rsyslog
#

- name: rsyslog routage
  copy: src=rsyslog.d/cuttlefish.conf dest=/etc/rsyslog.d/cuttlefish.conf
  notify: restart rsyslog
