---

- name: packages
  apt: pkg={{ item }}
  with_items:
      - postfix
      - ruby2.1
      - ruby
      - ruby-dev
      - libpq-dev
      - imagemagick
      - libmagickcore-dev
      - libmagickwand-dev
      - git
      - bundler
      - redis-server
      - rsync

- name: cuttlefish user
  user: name=cuttlefish
        state=present
        shell=/bin/bash

- name: ssh folder
  file: path=/home/cuttlefish.ssh
        state=directory

- name: root authorized keys
  command: cat /root/.ssh/authorized_keys
  register: authorized_root

- debug: var=authorized_root

- name: root can log as cuttlefish
  lineinfile: dest=/home/cuttlefish/.ssh/authorized_keys
              line="{{ item }}"
              create=yes
              owner=cuttlefish
  with_items: authorized_root.stdout_lines

- name: services
  copy: src=systemd/{{ item }} dest=/etc/systemd/system/{{ item }}
  with_items:
      - cuttlefish-smtp.service
      - cuttlefish-log.service
      - cuttlefish-workers.service
  notify: systemctl daemon-reload

