---

- name: copy source
  synchronize: src=../../../../..   dest=/home/
      rsync_opts="--exclude 'contrib' --exclude 'provisioning' --exclude='.git' --exclude='.vagrant' --exclude 'vendor'"

- name: bundle install
  command: bundle install --frozen --path=vendor --quiet

- name: database.yml
  template: src=database.yml.j2 dest=/home/cuttlefish/config/database.yml
